name: Docker Test

on:
  push:
    branches:
      - master 
  pull_request:

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v3

    - name: Build Docker image
      run:  docker build -t dls-style-transfer-bot .

    - name: Run tests inside container
      run:  docker run dls-style-transfer-bot